service: mail-test
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

resources:
  - ${file(./resources/sqs.yml)}

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

custom:
  baseName: ${self:service}-${self:provider.region}
  sqs-main: ${self:custom.baseName}-message-queue
  sqs-main-dlq: ${self:custom.baseName}-message-dead-letter-queue
  esbuild:
    packager: 'pnpm'
    bundle: true
    minify: true
    sourcemap: false
    keepNames: true

functions:
  - ${file(./resources/lambdas/worker.yml)}

